FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY res/dashboard/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY src/dashboard.py .

RUN mkdir -p templates

COPY src/templates/* templates/

CMD ["python", "dashboard.py"]
