FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY res/engine/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY src/broker.py src/loader.py src/engine.py src/trader.py ./

CMD [ "python", "engine.py" ]
